-- Q1
SELECT EMPNO,
       RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS "MASKING_EMPNO",
       ENAME,
       RPAD(SUBSTR(ENAME, 1, 1), LENGTH(ENAME), '*') AS "MASKING_ENAME"
FROM EMP
WHERE LENGTH(ENAME) = 5;

-- Q2
SELECT EMPNO, ENAME, SAL, TRUNC(SAL/21.5, 1), ROUND((SAL/21.5)/8, 1)
FROM EMP;

-- Q3
SELECT EMPNO, ENAME, HIREDATE,ADD_MONTHS(HIREDATE, 3) AS "R_JOB", NVL2(COMM, TO_CHAR(COMM), 'N/A') AS "COMM"
FROM EMP;
-- Q4-1 > 문자열로 변경하여 구분
SELECT EMPNO , ENAME , MGR ,
       CASE SUBSTR(TO_CHAR(MGR), 1, 2)
           WHEN '75' THEN '5555'
           WHEN '76' THEN '6666'
           WHEN '77' THEN '7777'
           WHEN '78' THEN '8888'
           ELSE NVL2(MGR, TO_CHAR(MGR), '0000')
END AS CHG_MGR
FROM EMP;


-- Q4-2 > LPAD, 숫자로 구분
SELECT EMPNO, ENAME, MGR,
       CASE
           WHEN MGR IS NULL THEN '0000'
           WHEN LPAD(MGR, 2) = 75 THEN '5555'
           WHEN LPAD(MGR, 2) = 76 THEN '6666'
           WHEN LPAD(MGR, 2) = 77 THEN '7777'
           WHEN LPAD(MGR, 2) = 78 THEN '8888'
           ELSE TO_CHAR(MGR)
           END AS "CHG_MGR"
FROM EMP;