-- Q1
SELECT *
FROM EMP
WHERE ENAME LIKE '%S'
ORDER BY ENAME asc;
-- Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

-- Q3
SELECT EMPNO , ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN (20, 30) AND SAL > 2000;

-- Q4
SELECT *
FROM EMP
WHERE NOT (2000 <= SAL AND SAL <= 3000);

-- Q5
SELECT ENAME , EMPNO , SAL , DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND SAL NOT BETWEEN 1000 AND 2000;

-- Q6
SELECT *
FROM EMP
WHERE COMM IS NULL AND
      JOB IN ('MANAGER', 'CLERK') AND
      NOT ENAME LIKE '_L%';